name: 'SLO test over YDB'
description: 'YDB SLO test for SDKs. Creates possible errors in cluster to check how SDK handles them.'
inputs:
  GITHUB_TOKEN:
    description: 'A token to authenticate on behalf of the GitHub App installed on your repository.'
    required: true
    default: ${{ github.token }}
  GITHUB_HEAD_REF:
    description: 'The head_ref or source branch of the pull request in a workflow run.'
    required: false
    default: ${{ github.head_ref }}
  GITHUB_BASE_REF:
    description: 'The base_ref or target branch of the pull request in a workflow run.'
    required: true
    default: ${{ github.base_ref || github.ref }}
  WORKLOAD_RUNNER:
    description: 'The command or executable name used to run the workload against the YDB database.'
    required: false
    default: "sleep 10"
  CHAOS_TEST_RUNNER:
    description: 'The command or executable name used to run the chaos testing against the YDB cluster.'
    required: false
    default: "sleep 10"
  # YDB_STORAGE_NODE_COUNT:
  #   description: 'The number of YDB storage nodes to create.'
  #   default: "1"
  YDB_DATABASE_NODE_COUNT:
    description: 'The number of YDB database nodes to create.'
    default: "3"
runs:
  using: 'node20'
  main: 'index.js'
