{
 "title": "SLO",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLO Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "inflight",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) {{jobName}} In flight"
    },
    {
     "expr": "oks",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) {{jobName}} OK"
    },
    {
     "expr": "not_oks",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) {{jobName}} not OK"
    }
   ]
  },
  {
   "title": "SLO Requests RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "irate(inflight[2s])",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) {{jobName}} In flight"
    },
    {
     "expr": "irate(oks[2s])",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) {{jobName}} OK"
    },
    {
     "expr": "irate(not_oks[2s])",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) {{jobName}} not OK"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Read Latencies (OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "latency{jobName=\"read\", status=\"ok\"}",
     "legendFormat": "{{sdk}}-{{sdkVersion}}-p{{quantile}}"
    }
   ]
  },
  {
   "title": "Write Latencies (OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "latency{jobName=\"write\", status=\"ok\"}",
     "legendFormat": "{{sdk}}-{{sdkVersion}}-p{{quantile}}"
    }
   ]
  },
  {
   "title": "Read Latencies (NOT OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "latency{jobName=\"read\", status=\"err\"}",
     "legendFormat": "{{sdk}}-{{sdkVersion}}-p{{quantile}}"
    }
   ]
  },
  {
   "title": "Write Latencies (NOT OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "latency{jobName=\"write\", status=\"err\"}",
     "legendFormat": "{{sdk}}-{{sdkVersion}}-p{{quantile}}"
    }
   ]
  }
 ]
}