{
 "title": "SLO",
 "time": { "from": "2022-12-27T15:09:07.303Z", "to": "2022-12-27T15:10:37.127Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLO Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "inflight",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) In flight"
    },
    {
     "expr": "oks{sdk=\"nodejs\"}",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) OK"
    },
    {
     "expr": "not_oks{sdk=\"nodejs\"}",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) not OK"
    }
   ]
  },
  {
   "title": "SLO Requests RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "delta(inflight[2s]) / 2",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) In flight"
    },
    { "expr": "delta(oks[2s]) / 2", "legendFormat": "({{sdk}}-{{sdkVersion}}) OK" },
    {
     "expr": "changes(not_oks{sdk=\"nodejs\"}[2s])",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) not OK"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Read Latencies (OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "latency{jobName=\"read\", status=\"ok\"}",
     "legendFormat": "{{sdk}}-p{{quantile}}"
    }
   ]
  },
  {
   "title": "Write Latencies (OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "latency{jobName=\"write\", status=\"ok\"}",
     "legendFormat": "{{sdk}}-p{{quantile}}"
    }
   ]
  },
  {
   "title": "Read Latencies (NOT OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "latency{jobName=\"read\", status=\"err\"}",
     "legendFormat": "{{sdk}}-p{{quantile}}"
    }
   ]
  },
  {
   "title": "Write Latencies (NOT OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "latency{jobName=\"write\", status=\"err\"}",
     "legendFormat": "{{sdk}}-p{{quantile}}"
    }
   ]
  }
 ]
}