x-template: &ydb-common
  image: cr.yandex/crptqonuodf51kdj7a7d/ydb:24.2.7
  restart: always
  hostname: localhost
  platform: linux/amd64
  privileged: true
  volumes:
    - ./cfg/config.yaml:/opt/ydb/cfg/config.yaml

name: ydb

services:

  static-0:
    <<: *ydb-common
    container_name: static-0
    command:
      - /opt/ydb/bin/ydbd
      - server
      - --grpc-port
      - "2135"
      - --mon-port
      - "8765"
      - --ic-port
      - "19001"
      - --yaml-config
      - /opt/ydb/cfg/config.yaml
      - --node
      - static
      - --label
      - deployment=docker
    ports:
      - 2135:2135
      - 8765:8765
      - 19001:19001
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/2135"
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s

  static-init:
    <<: *ydb-common
    restart: on-failure
    container_name: static-init
    command:
      - /opt/ydb/bin/ydbd
      - -s
      - grpc://localhost:2135
      - admin
      - blobstorage
      - config
      - init
      - --yaml-file
      - /opt/ydb/cfg/config.yaml
    depends_on:
      static-0:
        condition: service_healthy

  tenant-init:
    <<: *ydb-common
    restart: on-failure
    container_name: tenant-init
    command:
      - /opt/ydb/bin/ydbd
      - -s
      - grpc://localhost:2135
      - admin
      - database
      - /Root/slo
      - create
      - ssd:1
    depends_on:
      static-init:
        condition: service_completed_successfully

  dynamic-1:
    <<: *ydb-common
    container_name: dynamic-1
    command:
      - /opt/ydb/bin/ydbd
      - server
      - --grpc-port
      - "2136"
      - --mon-port
      - "8766"
      - --ic-port
      - "19002"
      - --yaml-config
      - /opt/ydb/cfg/config.yaml
      - --tenant
      - /Root/slo
      - --node-broker
      - grpc://localhost:2135
      - --label
      - deployment=docker
    ports:
      - 2136:2136
      - 8766:8766
      - 19002:19002
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/2136"
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s
    depends_on:
      static-0:
        condition: service_healthy
      static-init:
        condition: service_completed_successfully
      tenant-init:
        condition: service_completed_successfully

  dynamic-2:
    <<: *ydb-common
    container_name: dynamic-2
    command:
      - /opt/ydb/bin/ydbd
      - server
      - --grpc-port
      - "2137"
      - --mon-port
      - "8767"
      - --ic-port
      - "19003"
      - --yaml-config
      - /opt/ydb/cfg/config.yaml
      - --tenant
      - /Root/slo
      - --node-broker
      - grpc://localhost:2135
      - --label
      - deployment=docker
    ports:
      - 2137:2137
      - 8767:8767
      - 19003:19003
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/2137"
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s
    depends_on:
      static-0:
        condition: service_healthy
      static-init:
        condition: service_completed_successfully
      tenant-init:
        condition: service_completed_successfully

  dynamic-3:
    <<: *ydb-common
    container_name: dynamic-3
    command:
      - /opt/ydb/bin/ydbd
      - server
      - --grpc-port
      - "2138"
      - --mon-port
      - "8768"
      - --ic-port
      - "19004"
      - --yaml-config
      - /opt/ydb/cfg/config.yaml
      - --tenant
      - /Root/slo
      - --node-broker
      - grpc://localhost:2135
      - --label
      - deployment=docker
    ports:
      - 2138:2138
      - 8768:8768
      - 19004:19004
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/2138"
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s
    depends_on:
      static-0:
        condition: service_healthy
      static-init:
        condition: service_completed_successfully
      tenant-init:
        condition: service_completed_successfully

