apiVersion: ydb.tech/v1alpha1
kind: Database
metadata:
  name: database
spec:
  monitoring:
    enabled: true
    interval: 3s
  image:
    name: cr.yandex/crptqonuodf51kdj7a7d/ydb:${{VERSION}}
  domain: Root
  nodes: 3
  resources:
    storageUnits:
      - unitKind: ssd
        count: 2
  service:
    grpc:
      tls:
        enabled: false
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv4
    interconnect:
      tls:
        enabled: false
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv4
    status:
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv4
  additionalLabels:
    ydb-cluster: slo-storage
    ydb-cluster-monitor: slo-storage
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: ydb-cluster
                operator: In
                values:
                  - slo-storage
          topologyKey: "kubernetes.io/hostname"
  storageClusterRef:
    name: storage
