apiVersion: ydb.tech/v1alpha1
kind: Database
metadata:
  name: database-sample
spec:
  monitoring:
    enabled: true
    interval: 3s
  additionalLabels:
    ydb-cluster: slo-storage
    ydb-cluster-monitor: slo-storage
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: ydb-cluster
                operator: In
                values:
                  - slo-storage
          topologyKey: 'kubernetes.io/hostname'
  image:
    name: cr.yandex/crptqonuodf51kdj7a7d/ydb:${{VERSION}}
  nodes: 6
  resources:
    containerResources:
      limits:
        cpu: 1
    storageUnits:
      - count: 1
        unitKind: ssd
  storageClusterRef:
    name: storage-sample
