apiVersion: ydb.tech/v1alpha1
kind: Database
metadata:
  name: database
spec:
  image:
    name: cr.yandex/crptqonuodf51kdj7a7d/ydb:23.3.17
  domain: Root
  nodes: 3
  resources:
    storageUnits:
      - unitKind: ssd
        count: 2
  service:
    grpc:
      tls:
        enabled: false
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv4
    interconnect:
      tls:
        enabled: false
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv4
    status:
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv4
  additionalLabels:
    ydb-cluster: kind-database
    ydb-cluster-monitor: kind-database
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: ydb-cluster
                operator: In
                values:
                  - kind-database
          topologyKey: "kubernetes.io/hostname"
  storageClusterRef:
    name: storage
