apiVersion: ydb.tech/v1alpha1
kind: Database
metadata:
  name: database-sample
spec:
#  monitoring:
#    enabled: true
#    interval: 3s
  image:
    name: cr.yandex/crptqonuodf51kdj7a7d/ydb:${{VERSION}}
  nodes: 3
  resources:
    containerResources:
      limits:
        cpu: 1
    storageUnits:
      - count: 1
        unitKind: ssd
  storageClusterRef:
    name: storage-sample