apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ydb
spec:
  selector:
    matchLabels:
      app: ydb-operator
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: web