apiVersion: ydb.tech/v1alpha1
kind: Storage
metadata:
  name: storage
  namespace: ydb
spec:
  image:
    name: cr.yandex/crptqonuodf51kdj7a7d/ydb:${{VERSION}}
  domain: Root
  nodes: 3
  service:
    grpc:
      tls:
        enabled: false
      ipFamilies:
        - IPv4
    interconnect:
      tls:
        enabled: false
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv4
    status:
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv4
  additionalLabels:
    ydb-cluster: kind-storage
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: ydb-cluster
                operator: In
                values:
                  - kind-storage
          topologyKey: "kubernetes.io/hostname"
  erasure: mirror-3-dc
  dataStore: []
  configuration: |+
    static_erasure: mirror-3-dc
    host_configs:
      - drive:
          - path: SectorMap:1:1
            type: SSD
      - drive:
          - path: SectorMap:2:1
            type: SSD
      - drive:
          - path: SectorMap:3:1
            type: SSD
        host_config_id: 1
    domains_config:
      security_config:
        enforce_user_token_requirement: false
        administration_allowed_sids: 
          jorres
      domain:
      - name: Root
        storage_pool_types:
        - kind: ssd
          pool_config:
            box_id: 1
            erasure_species: mirror-3-dc
            kind: ssd
            pdisk_filter:
            - property:
              - type: SSD # device type to match host_configs.drive.type
            vdisk_kind: Default
      state_storage:
      - ring:
          node: [1, 2, 3]
          nto_select: 3
        ssid: 1
    table_service_config:
      sql_version: 1
    actor_system_config:
      executor:         
      - name: System    
        threads: 1
        type: BASIC
      - name: User      
        threads: 1
        type: BASIC
      - name: Batch     
        threads: 1      
        type: BASIC
      - name: IO        
        threads: 1
        time_per_mailbox_micro_secs: 100
        type: IO
      - name: IC        
        spin_threshold: 10
        threads: 4      
        time_per_mailbox_micro_secs: 100
        type: BASIC
      scheduler:
        progress_threshold: 10000
        resolution: 256
        spin_threshold: 0
    blob_storage_config:    # configuration of static blobstorage group.
      service_set:
        groups:
        - erasure_species: mirror-3-dc
          rings:
          - fail_domains:
            - vdisk_locations:
              - node_id: storage-0
                pdisk_category: SSD
                path: SectorMap:1:1
            - vdisk_locations:
              - node_id: storage-0
                pdisk_category: SSD
                path: SectorMap:2:1
            - vdisk_locations:
              - node_id: storage-0
                pdisk_category: SSD
                path: SectorMap:3:1
          - fail_domains:
            - vdisk_locations:
              - node_id: storage-1
                pdisk_category: SSD
                path: SectorMap:1:1
            - vdisk_locations:
              - node_id: storage-1
                pdisk_category: SSD
                path: SectorMap:2:1
            - vdisk_locations:
              - node_id: storage-1
                pdisk_category: SSD
                path: SectorMap:3:1
          - fail_domains:
            - vdisk_locations:
              - node_id: storage-2
                pdisk_category: SSD
                path: SectorMap:1:1
            - vdisk_locations:
              - node_id: storage-2
                pdisk_category: SSD
                path: SectorMap:2:1
            - vdisk_locations:
              - node_id: storage-2
                pdisk_category: SSD
                path: SectorMap:3:1
    channel_profile_config:
      profile:
      - channel:
        - erasure_species: mirror-3-dc
          pdisk_category: 0
          storage_pool_kind: ssd
        - erasure_species: mirror-3-dc
          pdisk_category: 0
          storage_pool_kind: ssd
        - erasure_species: mirror-3-dc
          pdisk_category: 0
          storage_pool_kind: ssd
        profile_id: 0
    grpc_config:
        port: 2135
