apiVersion: ydb.tech/v1alpha1
kind: Storage
metadata:
  name: storage
spec:
  monitoring:
    enabled: true
    interval: 3s
  image:
    name: cr.yandex/crptqonuodf51kdj7a7d/ydb:${{VERSION}}
  domain: Root
  nodes: 1
  service:
    grpc:
      tls:
        enabled: false
      ipFamilies:
        - IPv4
    interconnect:
      tls:
        enabled: false
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv4
    status:
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv4
  additionalLabels:
    ydb-cluster: kind-storage
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: ydb-cluster
                operator: In
                values:
                  - kind-storage
          topologyKey: "kubernetes.io/hostname"
  erasure: none
  dataStore: []
  configuration: |+
    static_erasure: none
    host_configs:
      - drive:
          - path: SectorMap:1:1
            type: SSD
        host_config_id: 1
    grpc_config:
      port: 2135
    domains_config:
      domain:
        - name: Root
          storage_pool_types:
            - kind: ssd
              pool_config:
                box_id: 1
                erasure_species: none
                kind: ssd
                pdisk_filter:
                  - property:
                      - type: SSD
                vdisk_kind: Default
      state_storage:
        - ring:
            node:
              - 1
            nto_select: 1
          ssid: 1
    actor_system_config:
      executor:
        - name: System
          spin_threshold: 0
          threads: 2
          type: BASIC
        - name: User
          spin_threshold: 0
          threads: 3
          type: BASIC
        - name: Batch
          spin_threshold: 0
          threads: 2
          type: BASIC
        - name: IO
          threads: 1
          time_per_mailbox_micro_secs: 100
          type: IO
        - name: IC
          spin_threshold: 10
          threads: 1
          time_per_mailbox_micro_secs: 100
          type: BASIC
      scheduler:
        progress_threshold: 10000
        resolution: 256
        spin_threshold: 0
    blob_storage_config:
      service_set:
        groups:
          - erasure_species: none
            rings:
              - fail_domains:
                  - vdisk_locations:
                      - node_id: 1
                        path: SectorMap:1:1
                        pdisk_category: SSD
    channel_profile_config:
      profile:
        - channel:
            - erasure_species: none
              pdisk_category: 0
              storage_pool_kind: ssd
            - erasure_species: none
              pdisk_category: 0
              storage_pool_kind: ssd
            - erasure_species: none
              pdisk_category: 0
              storage_pool_kind: ssd
          profile_id: 0
