apiVersion: batch/v1
kind: Job
metadata:
  name: ${{LANGUAGE_ID}}-wl-${{COMMAND}}
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 0
  template:
    metadata:
      name: ${{LANGUAGE_ID}}-wl-${{COMMAND}}
    spec:
      containers:
        - name: ${{LANGUAGE_ID}}-wl-${{COMMAND}}
          image: ${{DOCKER_IMAGE}}:latest
          imagePullPolicy: Never
          env:
            - name: YDB_ANONYMOUS_CREDENTIALS
              value: "1"
          args:
            - "${{COMMAND}}"
            - ${{ARGS}}
      restartPolicy: Never
