{
 "title": "SLO",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "SLO Requests RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(inflight[$__rate_interval]) > 0",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) {{jobName}} In flight"
    },
    {
     "expr": "rate(oks[$__rate_interval]) > 0",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) {{jobName}} OK"
    },
    {
     "expr": "rate(not_oks[$__rate_interval]) > 0",
     "legendFormat": "({{sdk}}-{{sdkVersion}}) {{jobName}} not OK"
    }
   ]
  },
  {
   "title": "Attempts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(1, rate(attempts_bucket[$__rate_interval]))",
     "legendFormat": "{{sdk}}-{{sdkVersion}} {{jobName}}-{{status}}"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Read Latencies (OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "latency{jobName=\"read\", status=\"ok\"} > 0",
     "legendFormat": "{{sdk}}-{{sdkVersion}}-p{{quantile}}"
    }
   ]
  },
  {
   "title": "Write Latencies (OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "latency{jobName=\"write\", status=\"ok\"} > 0",
     "legendFormat": "{{sdk}}-{{sdkVersion}}-p{{quantile}}"
    }
   ]
  },
  {
   "title": "Read Latencies (NOT OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "latency{jobName=\"read\", status=\"err\"} > 0",
     "legendFormat": "{{sdk}}-{{sdkVersion}}-p{{quantile}}"
    }
   ]
  },
  {
   "title": "Write Latencies (NOT OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "latency{jobName=\"write\", status=\"err\"} > 0",
     "legendFormat": "{{sdk}}-{{sdkVersion}}-p{{quantile}}"
    }
   ]
  }
 ]
}