
name: test-local-SLO
on: 
  workflow_dispatch:

jobs:
  test-slo:
    concurrency:
      group: slo-${{ github.ref }}

    runs-on: ubuntu-latest
    name: SLO test
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ydb-platform/ydb-php-sdk

      - name: Run SLO
        uses: ydb-platform/slo-tests@k8s-local
        env:
          DOCKER_REPO: ${{ secrets.SLO_DOCKER_REPO }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_CREDENTIALS_B64: ${{ secrets.SLO_AWS_CREDENTIALS }}
          AWS_CONFIG_B64: ${{ secrets.SLO_AWS_CONFIG }}
          s3_endpoint: ${{ secrets.SLO_S3_ENDPOINT }}
          s3_images_folder: ${{ vars.SLO_S3_IMAGES_FOLDER }}
          grafana_dashboard: dca60386-0d3d-43f5-a2af-5f3fd3e3b295
          grafana_dashboard_width: 2000
          grafana_dashboard_height: 2600
          ydb_version: 'newest'
          timeBetweenPhases: 30
          shutdownTime: 30

          language_id0: 'php'
          workload_path0: 'slo-workload'
          language0: 'php'
          workload_build_context0: ../.
          workload_build_options0: -f Dockerfile

      - uses: actions/upload-artifact@v4
        with:
          name: slo-logs
          path: logs/
